import = ["~/.config/alacritty/catpuccin.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 2, y = 2 }
startup_mode = "Maximized"

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
thickness = 0.18
vi_mode_style = "Block"
